#!/bin/bash

clear

wmake all src/lagrangian/basic
wmake all src/lagrangian/intermediate
wmake all src/lagrangian/turbulence
wmake all src/functionObjects/field
wmake all src/functionObjects/forces
wmake all applications/solvers/incompressible/pisoFoamSC
