#!/bin/bash

## Output
echo "${PWD##*/} Cleaning Initiated"

## Source Cleaning Functions
source ${WM_PROJECT_USER_DIR}/bin/tools/CleanFunctions

## Clean
cleanCase
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -rf constant/triSurface/*.eMesh > /dev/null 2>&1
rm -rf *.err > /dev/null 2>&1
rm -rf *.out > /dev/null 2>&1
rm -rf 0/cell* > /dev/null 2>&1
rm -rf LagrangianExtractionPlane/* > /dev/null 2>&1
rm -rf LagrangianSurfaceContamination/* > /dev/null 2>&1

## Output
echo "    Execution Time = ${SECONDS}s"
echo "${PWD##*/} Cleaning Complete"
echo
