#!/bin/bash

clear

## Call Cleaning Functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

## Clean
cleanCase
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -rf constant/triSurface/*.eMesh > /dev/null 2>&1
rm -rf *.err > /dev/null 2>&1
rm -rf *.out > /dev/null 2>&1
rm -rf 0/cell* > /dev/null 2>&1
sed -i 9q extractionData/extractionData
