#!/bin/bash

## Output
echo "${PWD##*/} Mesh Conversion Initiated"

## Conversion
ccm26ToFoam STAR_Mesh.ccm > log.ccm26ToFoam

## Quality Check
checkMesh -writeSets vtk > log.checkMesh

## Output
echo "${PWD##*/} Mesh Conversion Complete"
