#!/bin/bash

## Output
echo "${PWD##*/} Reconstruction Initiated"

# ## Reconstruct (Latest Time)
# reconstructPar -latestTime > log.reconstructParRunLatest

## Reconstruct (Full Case)
(foamListTimes; foamListTimes -processor) | sort -g | uniq -u | parallel -k -j 4 reconstructPar -newTimes -time {} > log.reconstructParRun

# ## Clean
# rm -rf processor* > /dev/null 2>&1

## Output
echo "    Execution Time = ${SECONDS}s"
echo "${PWD##*/} Reconstruction Complete"
echo
