#!/bin/bash

echo "${PWD##*/} Reconstruction Initiated"

## Reconstruction
reconstructPar > log.reconstructParRun

## Clean-up
rm -rf processor* > /dev/null 2>&1

## Output
echo "${PWD##*/} Reconstruction Complete"
