#!/bin/bash

## Output
echo "${PWD##*/} Case Initialising"

## Decompose
decomposePar > log.decomposeParRun

## Optimise
# mpirun -np 6 renumberMesh -parallel -overwrite > log.renumberMesh
mpirun -np 256 renumberMesh -parallel -overwrite > log.renumberMesh

# ## Initialise
# mpirun -np 6 potentialFoam -parallel > log.potentialFoam
# # mpirun -np 256 potentialFoam -parallel > log.potentialFoam

## Output
echo "    Execution Time = ${SECONDS}s"
echo "${PWD##*/} Initialisation Complete"
echo
