#!/bin/bash

## Initialise
echo "${PWD##*/} Case Initialising"

## Decompose
decomposePar > log.decomposeParRun

## renumberMesh
mpirun -np 4 renumberMesh -parallel -overwrite > log.renumberMesh
# mpirun -np 256 renumberMesh -parallel -overwrite > log.renumberMesh

# ## potentialFoam
# mpirun -np 4 potentialFoam -parallel > log.potentialFoam
# # mpirun -np 256 potentialFoam -parallel > log.potentialFoam

## Complete
echo
echo "    Execution Time = ${SECONDS}s"
echo
echo "${PWD##*/} Initialisation Complete"
echo
