#!/bin/bash

echo "${PWD##*/} Meshing Initiated"

## blockMesh
blockMesh > log.meshBlock
checkMesh -writeSets vtk > log.checkMeshBlock

## snappyHexMesh
surfaceFeatures > log.surfaceFeatures
decomposePar > log.decomposeParMesh
mpirun -np 6 snappyHexMesh -parallel > log.meshSnappy
# mpirun -np 280 snappyHexMesh -parallel > log.meshSnappy
mpirun -np 6 checkMesh -parallel -latestTime -writeSets vtk > log.checkMeshSnappy
# mpirun -np 280 checkMesh -parallel -latestTime -writeSets vtk > log.checkMeshSnappy
reconstructParMesh -latestTime > log.reconstructParMesh

## Clean-up
rm -rf constant/polyMesh > /dev/null 2>&1
cp -r $(foamListTimes -latestTime)/polyMesh constant
rm -rf $(foamListTimes -latestTime) > /dev/null 2>&1
rm -rf processor* > /dev/null 2>&1

## Output
echo "${PWD##*/} Meshing Complete"
